baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Lachlan Dwyer"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/perspective-checkerboard-1405614220yg1.jpg"]